# Build target and execute test cases
script:
 - mc _ cmake .
 - mc _ make
 - mc _ make test

# Install all required dependencies
install:
 - npm install -g mini-cross
 - mc _ echo 'Initialized container'

language: node_js

services:
 - docker

